package com.example.ecommerceconcept.utils

import com.example.ecommerceconcept.presentation.fragments.DetailsFragmentDirections
import com.example.ecommerceconcept.presentation.fragments.HomeStoreFragmentDirections

val HOME_TO_DETAILS = HomeStoreFragmentDirections.actionHomeStoreFragmentToDetailsFragment()

val DETAILS_TO_CART = DetailsFragmentDirections.actionDetailsFragmentToCartFragment()